import Image from "next/image";
import Head from "next/head";
import profilePic from "../../public/profilePic.png"

import { Work_Sans } from "next/font/google";
import Layout from "@/components/Layout";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-ws",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>G.Yao Portfolio</title>
        <meta
          name="description"
          content="Grace Yao professional porfolio generated by create next app"
        />
      </Head>
      <main
        className={`${workSans.variable} font-ws flex items-center text-dark w-full min-h-screen`}
      >
        <Layout>
          <h1>This is Home Bitches</h1>
          <div className="flex items-center justify-between w-full">
            <div>
              <Image src={profilePic} alt="GraceY" className="rounded-full" width={350} />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
